import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainLayout from '@/components/MainLayout'
import MenuContextProvider from '@/context/MenuContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cashier Next App',
  description: 'Generated by cashier next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MenuContextProvider>
       <MainLayout> {children} </MainLayout>
      </MenuContextProvider>
      </body>
    </html>
  )
}
